---
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: s3
  namespace: registry
data:
  REGISTRY_STORAGE_S3_ACCESSKEY: ZG9xxxxxxxxxxxxzdHJ5
  REGISTRY_STORAGE_S3_SECRETKEY: azNzxxxxxxxxxxxxIQ==
